FROM public.ecr.aws/lambda/python:latest

WORKDIR ${LAMBDA_TASK_ROOT}

COPY requirements.txt .

RUN pip3 install -r requirements.txt

COPY connect.py .
COPY lambda_function.py .

CMD ["lambda_function.lambda_handler"]